action_dimensionality: continuous
batch_size: 128
cost_model: weighted_threshold
distance_threshold: 15
domain_length: 200
entropy_threshold: 0
eps_decay: 16666.666666666668
eps_end: 0.1
eps_start: 0.9
filter_length: 50
filter_type: particle
gamma: 0.995
include_velocity: true
lambda_1: 1
lambda_2: 1
lambda_3: 0
lr_Q: 0.001
lr_mu: 0.0001
memory_size: 100000
nb_act_repeat: 1
nb_directions: 12
nb_episodes: 100000
nb_max_episode_steps: 100
nb_particles: 2000
nb_warmup_steps: 1000
notes: DDPG algo
phi_length: 1
reward_scaling: 0.1
run: ddpg_run_01
sensor_sd: 5.0
sensor_type: bearing_only
target_max_step: 1.7
target_update: 0.001
tracking_threshold: 0
